#define REDIS_GIT_SHA1 "86dde643"
#define REDIS_GIT_DIRTY "0"
#define REDIS_BUILD_ID "xiaohai-1663644194"
#include "version.h"
#define REDIS_BUILD_ID_RAW REDIS_VERSION REDIS_BUILD_ID REDIS_GIT_DIRTY REDIS_GIT_SHA1
